packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  svelte-preprocess: true
  '@sveltejs/kit': true
minimumReleaseAgeExclude:
  - sveltekit-flash-message@3.0.0-next.0
overrides:
  sveltekit-flash-message: link:../sveltekit-flash-message
