packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  svelte-preprocess: true
  '@sveltejs/kit': true
patchedDependencies:
  sveltekit-flash-message@2.4.6: patches/sveltekit-flash-message.patch
